export default {
  CLEAN_STORE: 'CLEAN_STORE',

  IS_CANVAS_SUPPORTED: 'IS_CANVAS_SUPPORTED',
  NEW_STEP: 'NEW_STEP',
  CHANGE_GAME_RESULT: 'CHANGE_GAME_RESULT',

  POPUP_APPEAR: 'POPUP_APPEAR',
  POPUP_DISAPPEAR: 'POPUP_DISAPPEAR',
  POPUP_BTN_CLICK: 'POPUP_BTN_CLICK',
  POPUP_LINK_CLICK: 'POPUP_LINK_CLICK',
  POPUP_CONTENT: 'POPUP_CONTENT'
};
