export default {
  CLEAN_STORE: 'CLEAN_STORE',
  INCREASE: 'INCREASE',
  DECREASE: 'DECREASE',

  SERVER_ERROR: 'SERVER_ERROR',

  POPUP_APPEAR: 'POPUP_APPEAR',
  POPUP_DISAPPEAR: 'POPUP_DISAPPEAR',
  POPUP_BTN_CLICK: 'POPUP_BTN_CLICK',
  POPUP_LINK_CLICK: 'POPUP_LINK_CLICK',
  POPUP_CONTENT: 'POPUP_CONTENT'
};
